"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase/supabaseClient";
import { DASHBOARD_CONFIG, isDashboardTab, type DashboardTab } from "@/lib/fisheries-dashboard/config";
import type { DashboardSourceUpload, DashboardWorkflow, DashboardWorkflowMetadata } from "@/lib/fisheries-dashboard/types";
import DashboardVisualizationPreview from "./DashboardVisualizationPreview";
import SpinnerLoading from "../SpinnerLoading";

export default function PublicDashboardWorkflow({ workflowId }: { workflowId: string }) {
  const [workflow, setWorkflow] = useState<DashboardWorkflow | null>(null); const [sources, setSources] = useState<DashboardSourceUpload[]>([]); const [sourcePartnerId, setSourcePartnerId] = useState<string>(); const [active, setActive] = useState<DashboardTab | null>(null); const [error, setError] = useState("");
  useEffect(() => { void Promise.all([supabase.from("datasets").select("id,user_id,label,column_config,published,created_at,updated_at").eq("id", workflowId).eq("kind", "dashboard").eq("published", "approved").single(), supabase.from("dataset_import_batches").select("id,dataset_id,source_type,row_count,compatible_tabs,created_at").eq("dataset_id", workflowId).not("source_type", "is", null)]).then(([workflowResult, sourceResult]) => { if (workflowResult.error) { setError("Dashboard tidak ditemukan atau belum dipublikasikan."); return; } const data = workflowResult.data; const container = (data.column_config && typeof data.column_config === "object" ? data.column_config : {}) as { dashboardWorkflow?: DashboardWorkflowMetadata }; const meta = container.dashboardWorkflow; if (!meta) { setError("Konfigurasi dashboard tidak valid."); return; } const row: DashboardWorkflow = { id: data.id, user_id: data.user_id, label: data.label, selected_tabs: meta.selectedTabs, current_stage: meta.currentStage, active_tab: meta.activeTab, upload_status: meta.uploadStatus, visualization_status: meta.visualizationStatus, publication_status: data.published, created_at: data.created_at, updated_at: data.updated_at }; setWorkflow(row); setSourcePartnerId(meta.sourcePartnerId); const mapped = (sourceResult.data ?? []).map((source) => ({ id: source.id, workflow_id: source.dataset_id, source_type: source.source_type, source_table: source.source_type === "trip" ? "dataset_fish_trip" : "dataset_fish_length", row_count: source.row_count, compatible_tabs: source.compatible_tabs, created_at: source.created_at })) as DashboardSourceUpload[]; if (meta.sourcePartnerId && mapped.length === 0) mapped.push({ id: `partner:${meta.sourcePartnerId}:trip`, workflow_id: workflowId, source_type: "trip", source_table: "dataset_fish_trip", row_count: 0, compatible_tabs: ["cpue","totallanding","composition"], created_at: data.updated_at }, { id: `partner:${meta.sourcePartnerId}:length`, workflow_id: workflowId, source_type: "length", source_table: "dataset_fish_length", row_count: 0, compatible_tabs: ["lengthfrequency"], created_at: data.updated_at }); setSources(mapped); setActive(row.selected_tabs.find(isDashboardTab) ?? null); }); }, [workflowId]);
  if (error) return <p className="rounded-xl bg-rose-50 p-5 text-rose-800">{error}</p>;
  if (!workflow || !active) return <div className="flex justify-center p-10"><SpinnerLoading size="sm" color="black" /></div>;
  const source = sources.find((item) => item.source_type === DASHBOARD_CONFIG[active].templateType);
  return <section className="space-y-6"><header><p className="text-sm font-semibold text-sky-800">Dashboard Perikanan</p><h1 className="text-3xl font-bold">{workflow.label}</h1><p className="mt-2 text-sm text-stone-500">Terakhir diperbarui: {new Intl.DateTimeFormat("id-ID", { dateStyle: "long" }).format(new Date(workflow.updated_at))}</p></header><nav className="flex flex-wrap gap-2">{workflow.selected_tabs.filter(isDashboardTab).map((tab) => <button key={tab} onClick={() => setActive(tab)} className={`rounded-lg border px-4 py-2 shadow-sm ${active === tab ? "bg-sky-800 text-white" : "bg-white"}`}>{DASHBOARD_CONFIG[tab].label}</button>)}</nav><article className="rounded-2xl border bg-white p-5 shadow-md"><h2 className="mb-4 text-xl font-bold">{DASHBOARD_CONFIG[active].label}</h2><DashboardVisualizationPreview tab={active} userId={workflow.user_id} /></article></section>;
}

