export const countryList = [
  { name: "Afghanistan", value: "afghanistan" },
  { name: "Albania", value: "albania" },
  { name: "Algeria", value: "algeria" },
  { name: "Andorra", value: "andorra" },
  { name: "Angola", value: "angola" },
  { name: "Antigua and Barbuda", value: "antigua and barbuda" },
  { name: "Argentina", value: "argentina" },
  { name: "Armenia", value: "armenia" },
  { name: "Australia", value: "australia" },
  { name: "Austria", value: "austria" },
  { name: "Azerbaijan", value: "azerbaijan" },
  { name: "Bahamas", value: "bahamas" },
  { name: "Bahrain", value: "bahrain" },
  { name: "Bangladesh", value: "bangladesh" },
  { name: "Barbados", value: "barbados" },
  { name: "Belarus", value: "belarus" },
  { name: "Belgium", value: "belgium" },
  { name: "Belize", value: "belize" },
  { name: "Benin", value: "benin" },
  { name: "Bhutan", value: "bhutan" },
  { name: "Bolivia", value: "bolivia" },
  {
    name: "Bosnia and Herzegovina",
    value: "bosnia and herzegovina",
  },
  { name: "Botswana", value: "botswana" },
  { name: "Brazil", value: "brazil" },
  { name: "Brunei", value: "brunei" },
  { name: "Bulgaria", value: "bulgaria" },
  { name: "Burkina Faso", value: "burkina faso" },
  { name: "Burundi", value: "burundi" },
  { name: "Cabo Verde", value: "cabo verde" },
  { name: "Cambodia", value: "cambodia" },
  { name: "Cameroon", value: "cameroon" },
  { name: "Canada", value: "canada" },
  {
    name: "Central African Republic",
    value: "central african republic",
  },
  { name: "Chad", value: "chad" },
  { name: "Chile", value: "chile" },
  { name: "China", value: "china" },
  { name: "Colombia", value: "colombia" },
  { name: "Comoros", value: "comoros" },
  { name: "Costa Rica", value: "costa rica" },
  { name: "Côte d'Ivoire", value: "cote d'ivoire" },
  { name: "Croatia", value: "croatia" },
  { name: "Cuba", value: "cuba" },
  { name: "Cyprus", value: "cyprus" },
  { name: "Czechia", value: "czechia" },
  {
    name: "Democratic Republic of the Congo",
    value: "democratic republic of the congo",
  },
  { name: "Denmark", value: "denmark" },
  { name: "Djibouti", value: "djibouti" },
  { name: "Dominica", value: "dominica" },
  {
    name: "Dominican Republic",
    value: "dominican republic",
  },
  { name: "Ecuador", value: "ecuador" },
  { name: "Egypt", value: "egypt" },
  { name: "El Salvador", value: "el salvador" },
  {
    name: "Equatorial Guinea",
    value: "equatorial guinea",
  },
  { name: "Eritrea", value: "eritrea" },
  { name: "Estonia", value: "estonia" },
  { name: "Eswatini", value: "eswatini" },
  { name: "Ethiopia", value: "ethiopia" },
  { name: "Fiji", value: "fiji" },
  { name: "Finland", value: "finland" },
  { name: "France", value: "france" },
  { name: "Gabon", value: "gabon" },
  { name: "Gambia", value: "gambia" },
  { name: "Georgia", value: "georgia" },
  { name: "Germany", value: "germany" },
  { name: "Ghana", value: "ghana" },
  { name: "Greece", value: "greece" },
  { name: "Grenada", value: "grenada" },
  { name: "Guatemala", value: "guatemala" },
  { name: "Guinea", value: "guinea" },
  { name: "Guinea-Bissau", value: "guinea-bissau" },
  { name: "Guyana", value: "guyana" },
  { name: "Haiti", value: "haiti" },
  { name: "Honduras", value: "honduras" },
  { name: "Hungary", value: "hungary" },
  { name: "Iceland", value: "iceland" },
  { name: "India", value: "india" },
  { name: "Indonesia", value: "indonesia" },
  { name: "Iran", value: "iran" },
  { name: "Iraq", value: "iraq" },
  { name: "Ireland", value: "ireland" },
  { name: "Israel", value: "israel" },
  { name: "Italy", value: "italy" },
  { name: "Jamaica", value: "jamaica" },
  { name: "Japan", value: "japan" },
  { name: "Jordan", value: "jordan" },
  { name: "Kazakhstan", value: "kazakhstan" },
  { name: "Kenya", value: "kenya" },
  { name: "Kiribati", value: "kiribati" },
  { name: "Kuwait", value: "kuwait" },
  { name: "Kyrgyzstan", value: "kyrgyzstan" },
  { name: "Laos", value: "laos" },
  { name: "Latvia", value: "latvia" },
  { name: "Lebanon", value: "lebanon" },
  { name: "Lesotho", value: "lesotho" },
  { name: "Liberia", value: "liberia" },
  { name: "Libya", value: "libya" },
  { name: "Liechtenstein", value: "liechtenstein" },
  { name: "Lithuania", value: "lithuania" },
  { name: "Luxembourg", value: "luxembourg" },
  { name: "Madagascar", value: "madagascar" },
  { name: "Malawi", value: "malawi" },
  { name: "Malaysia", value: "malaysia" },
  { name: "Maldives", value: "maldives" },
  { name: "Mali", value: "mali" },
  { name: "Malta", value: "malta" },
  {
    name: "Marshall Islands",
    value: "marshall islands",
  },
  { name: "Mauritania", value: "mauritania" },
  { name: "Mauritius", value: "mauritius" },
  { name: "Mexico", value: "mexico" },
  { name: "Micronesia", value: "micronesia" },
  { name: "Moldova", value: "moldova" },
  { name: "Monaco", value: "monaco" },
  { name: "Mongolia", value: "mongolia" },
  { name: "Montenegro", value: "montenegro" },
  { name: "Morocco", value: "morocco" },
  { name: "Mozambique", value: "mozambique" },
  { name: "Myanmar", value: "myanmar" },
  { name: "Namibia", value: "namibia" },
  { name: "Nauru", value: "nauru" },
  { name: "Nepal", value: "nepal" },
  { name: "Netherlands", value: "netherlands" },
  { name: "New Zealand", value: "new zealand" },
  { name: "Nicaragua", value: "nicaragua" },
  { name: "Niger", value: "niger" },
  { name: "Nigeria", value: "nigeria" },
  { name: "North Korea", value: "north korea" },
  { name: "North Macedonia", value: "north macedonia" },
  { name: "Norway", value: "norway" },
  { name: "Oman", value: "oman" },
  { name: "Pakistan", value: "pakistan" },
  { name: "Palau", value: "palau" },
  { name: "Palestine", value: "palestine" },
  { name: "Panama", value: "panama" },
  {
    name: "Papua New Guinea",
    value: "papua new guinea",
  },
  { name: "Paraguay", value: "paraguay" },
  { name: "Peru", value: "peru" },
  { name: "Philippines", value: "philippines" },
  { name: "Poland", value: "poland" },
  { name: "Portugal", value: "portugal" },
  { name: "Qatar", value: "qatar" },
  {
    name: "Republic of the Congo",
    value: "republic of the congo",
  },
  { name: "Romania", value: "romania" },
  { name: "Russia", value: "russia" },
  { name: "Rwanda", value: "rwanda" },
  {
    name: "Saint Kitts and Nevis",
    value: "saint kitts and nevis",
  },
  { name: "Saint Lucia", value: "saint lucia" },
  {
    name: "Saint Vincent and the Grenadines",
    value: "saint vincent and the grenadines",
  },
  { name: "Samoa", value: "samoa" },
  { name: "San Marino", value: "san marino" },
  {
    name: "São Tomé and Príncipe",
    value: "sao tome and principe",
  },
  { name: "Saudi Arabia", value: "saudi arabia" },
  { name: "Senegal", value: "senegal" },
  { name: "Serbia", value: "serbia" },
  { name: "Seychelles", value: "seychelles" },
  { name: "Sierra Leone", value: "sierra leone" },
  { name: "Singapore", value: "singapore" },
  { name: "Slovakia", value: "slovakia" },
  { name: "Slovenia", value: "slovenia" },
  { name: "Solomon Islands", value: "solomon islands" },
  { name: "Somalia", value: "somalia" },
  { name: "South Africa", value: "south africa" },
  { name: "South Korea", value: "south korea" },
  { name: "South Sudan", value: "south sudan" },
  { name: "Spain", value: "spain" },
  { name: "Sri Lanka", value: "sri lanka" },
  { name: "Sudan", value: "sudan" },
  { name: "Suriname", value: "suriname" },
  { name: "Sweden", value: "sweden" },
  { name: "Switzerland", value: "switzerland" },
  { name: "Syria", value: "syria" },
  { name: "Tajikistan", value: "tajikistan" },
  { name: "Tanzania", value: "tanzania" },
  { name: "Thailand", value: "thailand" },
  { name: "Timor-Leste", value: "timor-leste" },
  { name: "Togo", value: "togo" },
  { name: "Tonga", value: "tonga" },
  {
    name: "Trinidad and Tobago",
    value: "trinidad and tobago",
  },
  { name: "Tunisia", value: "tunisia" },
  { name: "Türkiye", value: "turkiye" },
  { name: "Turkmenistan", value: "turkmenistan" },
  { name: "Tuvalu", value: "tuvalu" },
  { name: "Uganda", value: "uganda" },
  { name: "Ukraine", value: "ukraine" },
  {
    name: "United Arab Emirates",
    value: "united arab emirates",
  },
  { name: "United Kingdom", value: "united kingdom" },
  { name: "United States", value: "united states" },
  { name: "Uruguay", value: "uruguay" },
  { name: "Uzbekistan", value: "uzbekistan" },
  { name: "Vanuatu", value: "vanuatu" },
  { name: "Vatican City", value: "vatican city" },
  { name: "Venezuela", value: "venezuela" },
  { name: "Vietnam", value: "vietnam" },
  { name: "Yemen", value: "yemen" },
  { name: "Zambia", value: "zambia" },
  { name: "Zimbabwe", value: "zimbabwe" },
] as const;

export type CountryValue = (typeof countryList)[number]["value"];
